version: '3.9'

services:
  backend:
    container_name: spring-integration
    image: bastinjul/spring-integration
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8080"